import { useGLTF } from '@react-three/drei'
import { Physics, RigidBody } from '@react-three/rapier'
import Dolls from './Dolls.jsx'
import Walls from './Walls.jsx'
import Claw from './Claw.jsx'
import BottomBox from './BottomBox.jsx'

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

export function Machine() {
  return (
    <Physics debug={false} gravity={[0, -9.81, 0]} position={[0, -1, 0]}>
      <RigidBody>
        <mesh scale={[0.1, 0.1, 0.1]} position={[0, 2, 0]}>
          <boxGeometry />
          <meshBasicMaterial color="red" />
        </mesh>
      </RigidBody>
      <group dispose={null}>
        <BottomBox />
        <Claw />
      </group>
      <Walls />
      <Dolls />
    </Physics>
  )
}

useGLTF.preload('/model.glb')
