/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/model.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.floor.geometry}
        material={materials['Material.001']}
        position={[0, 0.843, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.glassA.geometry}
        material={materials.glass}
        position={[-0.137, 0.967, 0.319]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.glassB.geometry}
        material={materials.glass}
        position={[-0.315, 0.967, 0.129]}
        rotation={[0, -1.571, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.clawA.geometry}
        material={materials.arm}
        position={[0, 1.555, 0]}
        rotation={[0, 0, -0.611]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.clawB.geometry}
        material={materials.arm}
        position={[0, 1.555, 0]}
        rotation={[Math.PI, Math.PI / 3, 2.531]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.clawC.geometry}
        material={materials.arm}
        position={[0, 1.555, 0]}
        rotation={[Math.PI, -Math.PI / 3, 2.531]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube007.geometry}
        material={materials.arm}
        position={[0, 1.73, 0]}
      />
    </group>
  )
}

useGLTF.preload('/model.glb')
